### ISSUE TITLE
JS - Vibe, Food, Time Sorting

### ISSUE THREAD

**Issue by johnshaff** [mikeybkats/H2#2]
Section two needs to have three event buttons for vibe, food, and time that when pressed the event handler must resort the list in the following ways:
- Vibe: sorts entire list by vibe category
- Food: sorts entire list by whether or not the restaurant offers food during their H2
- Time: sorts back to default sorting which is time remaining on happy hour or time till the earliest happy hour

**Comment by mikeybkats** [comment]
@johnshaff I think we should have a chat about functionality for the vibe feature. Since how would it normally sort by vibe? Alphabetically? 

Here is my proposal:

Limit the types of vibe to 5 types. When user clicks vibe there are dropdown options. Is this still within scope? 

![image](https://cloud.githubusercontent.com/assets/7930539/15631144/25ef157e-250e-11e6-8545-4c90a767d0f6.png)

**Comment by johnshaff** [comment]
Still working on sorting. Removing things from the DOM is finicky. Sorting everything by the categories we already have: time, vibe, food... should be MVP. Doing another sort within the aforementioned sort should be a stretch goal.

**Comment by mikeybkats** [comment]
By what method will the list sort when the user clicks the vibe sorting option?
